### PR TITLE
BUG/GRID-224:

### PR DESCRIPTION
**Pull request by Dwaynekj**
@joneit 
There are some bugs with when trying to resize columns relating to ._setHeader in JSON.js being undefined. 
This will likely block testing the column drag fix

### CODE REVIEW

**Comment by joneit** [comment]
hmmm i thought you told me you couldn't reproduce that bug anymore?

**Comment by joneit** [comment]
did it go away or not? can you make it happen again? since the bug had to do with resize, so really not connected with this work? was it pre-existing? can we be put it in a new ticket?

**Comment by Dwaynekj** [comment]
I've been unable to reproduce the bug (both on this branch and develop). If I spot it again, I'll create a ticket

**Comment by joneit** [comment]
and the comment on line 507 please

**Comment by Dwaynekj** [comment]
Done. Btw you can comment directly on line numbers

**Pull request merged**
