### PR TITLE
GRID-458: Hidden columns excluded from schema

### PR DESCRIPTION
**Pull request by joneit**
For details see:
1. The extended comment on commit 3e9db31
2. The [Jira ticket](https://appoji.jira.com/browse/GRID-458)

### CODE REVIEW

**Comment by joneit** [comment]
@Dwaynekj Self-approving this in the interests of getting a release together. Please review it nevertheless when you get back. Thanks.

**Comment by Dwaynekj** [comment]
A Release for when? The next release is planned for the end of the sprint

**Comment by Dwaynekj** [comment]
Lets not do this anymore please

**Comment by Dwaynekj** [comment]
Disregard old comment. And sure thing

**Pull request merged**
