### PR TITLE
GRID-288: Add dataRow and columnName to valOrFunc

### PR DESCRIPTION
**Pull request by joneit**

### CODE REVIEW

**Comment by RaghavPro** [comment]
Just what I wanted. 👍

**Comment by joneit** [comment]
@RaghavPro New version 1.0.7 includes 2 params on the calculator function call: dataRow, columnName.

**Comment by RaghavPro** [comment]
@joneit Great! 
Would like to know your thoughts on #186

**Comment by joneit** [comment]
@RaghavPro It is in our new (current) sprint (for v1.0.8, to be released in 3 weeks).

**Pull request merged**
